@startuml

start
if (Has selected Jurisdiction?) then (yes)
  label lbl_login
  repeat
    if (Has sessionToken?) then (no)
      :LoginUIComponent;
    endif
  repeat while( Has sessionToken) is (no)
  :MainLobbyUIComponent;
  stop
else (no)
  :StateChooserUIComponent;
  goto lbl_login
endif
note left
  * Bullet list
  * Second item
  ** hello....
end note

@enduml
